[package]
name = "prooheckcp/roquest"
description = ""
version = "0.0.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Prooheckcp"]
exclude = ["**"]
include = [
    "default.project.json", 
    "RoQuest", 
    "RoQuest/*",
    "wally.lock", 
    "wally.toml",
]