name: Wally

on:
  push:
    branches: [main]

jobs:

  publish:
    name: Publish to Wally
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Aftman
      uses: ok-nick/setup-aftman@v0.4.2

    - name: Publish
      run: |
        wally login --token ${{ secrets.MOONWAVE_TOKEN }}
        wally publish

    env:
      GITHUB_TOKEN: ${{ secrets.MOONWAVE_TOKEN }}

